
service: stripe-eventbridge
frameworkVersion: ">=1.54.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage,'dev'}
  region: us-west-2
  endpointType: EDGE
  logs:                # Enable CloudWatch logs
    restApi: true
    httpApi: true
  tracing:             # Enable X-Ray tracing
    apiGateway: true

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource: "${cf:stripe-eventbridge-deps-${self:provider.stage}.StripeWebhookSecretArn}"
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource: ${cf:stripe-eventbridge-deps-${self:provider.stage}.SNSTargetForFailedEvents}
    - Effect: "Allow"
      Action:
        - "events:PutEvents"
      Resource: "*"

functions:
  stripe-webhook:
    handler: handler.stripeWebhook
    events:
      - httpApi:
          path: /stripe/webhook
          method: POST
          async: false
    environment:
      FAILURE_SNS: ${cf:stripe-eventbridge-deps-${self:provider.stage}.SNSTargetForFailedEvents}
      EVENT_BRIDGE: "stripe-${self:provider.stage}"
      ENDPOINT_SECRET: "${cf:stripe-eventbridge-deps-${self:provider.stage}.StripeWebhookSecretArn}"
    memorySize: 192
    timeout: 29