---
stripe-webhook-endpoint-secret: dev/stripe/stripe-webhook-endpoint-secret
stripe-event-failed-to-validate-sns-name: stripe-event-failed-to-validate
stripe-replay-sqs-queue-name: stripe-replay-queue-dev