
service: stripe-eventbridge-deps
frameworkVersion: ">=1.54.0 <2.0.0"

provider:
  name: aws
  stage: ${opt:stage,'dev'}
  region: us-west-2

resources:
  Resources:

    NotifyStripeWebhookEventFailedToValidate:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: stripe-webhook-event-failed-to-validate
        TopicName: ${file(./config-${self:provider.stage}.yml):stripe-event-failed-to-validate-sns-name}

    StripeWebhookSecret:
      Type: AWS::SecretsManager::Secret
      Properties:
        Description: This is the signing secret that is used to validate that incoming webhook events are from Stripe
        Name: ${file(./config-${self:provider.stage}.yml):stripe-webhook-endpoint-secret}

  Outputs:
    SNSTargetForFailedEvents:
      Value:
        Ref: NotifyStripeWebhookEventFailedToValidate
    StripeWebhookSecretArn:
      Value:
        Ref: StripeWebhookSecret
